spring.application.name=smarttodo

spring.datasource.url=jdbc:mysql://localhost:3306/smarttodo_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=[Username]
spring.datasource.password=[your Password]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=[Secret key]
app.jwt.expiration-ms=86400000
